version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          name: install gems
          command: bundle install --jobs=4
      - run:
          name: Install Code Climate Test Reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: test
          command: |
            ./cc-test-reporter before-build
            bundle exec rspec
            ./cc-test-reporter after-build -t simplecov --id d6831812c2f25cf76a515096a29fa2acca15b4d7d254dd52c3937a6ce31906a2
    environment:
      RACK_ENV: test
      APP_ROOT: /home/circleci/project
      CC_TEST_REPORTER_ID: d6831812c2f25cf76a515096a29fa2acca15b4d7d254dd52c3937a6ce31906a2
